services:
  api:
    build: .
    container_name: messenger-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    restart: unless-stopped
    build:
      context: .
      dockerfile: postgres/Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
